services:
  mysql:
    image: mysql:8.0
    container_name: Helper-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: HelperDb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Helper-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=HelperDb;user=root;password=rootpassword
      - GigaChat__ClientId=019adb03-4656-7997-927e-e8e6c97661e6
      - GigaChat__ClientSecret=5e18f373-ea91-4d10-a5a1-471201c2af02
      - GigaChat__Scope=GIGACHAT_API_PERS
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data: